backend:
  build: ./backend
  command: bash start.sh
  volumes:
    - ./backend:/app
    - ~/.ssh/:/root/.ssh
    - ./image_uploads:/image_uploads
  ports:
    - "3000"
  links:
    - postgres
    - redis

background:
  build: ./background
  command: bash start.sh
  ports:
    - "3000"
  volumes:
    - ./background:/app
    - ~/.ssh/:/root/.ssh
  links:
    - redis
    - postgres

nginx:
  build: ./nginx
  command: nginx -g 'daemon off;'
  ports:
    - "3000:80"
  environment:
    - NGINX_HOST=127.0.0.1
    - NGINX_PORT=80
  links:
    - background
    - backend
    - frontend
  volumes:
    - ./backend:/app
    - ./image_uploads:/images

postgres:
  image: macadmins/postgres
  ports:
    - '5432:5432'
  environment:
    - DB_NAME=postgres
    - DB_PASS=1234
  volumes:
    - ./db:/var/lib/postgresql/data

frontend:
  build: ./frontend
  entrypoint: []
  command: ember server
  volumes:
    - ./frontend:/myapp
    - ~/.ssh/:/root/.ssh
  links:
    - backend
  ports:
    - "4200"
    - "7357"

redis:
  image: redis
  ports:
    - '6379:6379'