nginx:
  build: ./nginx
  command: nginx -g 'daemon off;'
  ports:
    - "3000:80"
  environment:
    - NGINX_HOST=127.0.0.1
    - NGINX_PORT=80
  links:
    - client

client:
  build: ./client
  entrypoint: []
  command: ember server
  volumes:
    - ./client:/myapp
    - ~/.ssh/:/root/.ssh
  ports:
    - "4200"
    - "7357"

ejabberd:
  image: rroemhild/ejabberd
  ports:
    - 5222:5222
    - 5269:5269
    - 5280:5280
  environment:
    - EJABBERD_ADMINS=admin@localhost
    - EJABBERD_USERS=admin@localhost:password4321